### ISSUE TITLE
Plain eval is used without transpilation. Ts handlers do not work

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/bun-js-docker-isolation-provider#1]
# Description
Plain eval is used without transpilation: https://github.com/deep-foundation/bun-js-docker-isolation-provider/blob/f651fd5658f9cf858c10159b3aa8044d5a8a7be5/index.ts#L24
We have to transpile code by using Bun and then eval that code until Bun.eval is developer by bun team (https://github.com/oven-sh/bun/issues/5105)

# Example Of Non-Working Typescript Handler
## Handler Code
```ts
import { DeepClient } from "@deep-foundation/deeplinks/imports/client.js";
import { Link } from "@deep-foundation/deeplinks/imports/minilinks.js";
import { DeepClientInstance } from "@deep-foundation/deeplinks/imports/client";

async (options: {
  deep: DeepClient;
  data: {
    newLink: Link<number>;
  };
}) => {
    return 5
};
```

## Error
```
{
  "line": 9,
  "stack": "SyntaxError: Unexpected token '{'. import call expects one or two arguments.\n    at eval (native)\n    at memoized (/node_modules/lodash/memoize.js:62:21)\n    at makeFunction (/index.ts:24:20)\n    at <anonymous> (/index.ts:70:43)\n    at processTicksAndRejections (:1:1302)",
  "column": 30,
  "message": "Unexpected token '{'. import call expects one or two arguments.",
  "sourceURL": "/node_modules/lodash/memoize.js",
  "originalLine": 9,
  "originalColumn": 30
}
```

## Additional Information
Non-ts handler is working:
```js
async () => {
  return 5
}
```
Links in deepcase:
![image](https://github.com/deep-foundation/bun-js-docker-isolation-provider/assets/66206278/f3d41301-c0b1-48d0-b178-37b4677c21c7)

**Comment by Archer-Lotos** [comment]
# Fix your Handler Code


```ts
async ({deep, data}: {
  deep: DeepClient;
  data: {
    newLink: Link<number>;
  };
}) => {
    return await deep.insert({
        "type_id": 58,
        "from_id": 0,
        "to_id": 0
    });
}
```
